### ISSUE TITLE
Wrong type 'Result' in the pub.dev documentation

### ISSUE THREAD

**Issue by RukshanJS** [MasahiroLittleforest/overlapping_time#7]
In the https://pub.dev/packages/overlapping_time page, for the `DateTimeRange`, in the code provided there is a `Result` type, which gives an error. When replacing `Result` with `ComparingResult`, it is solved. I'm using `overlapping_time: ^0.1.0-nullsafety.0`.

Suggession : Please update the documentation at https://pub.dev/packages/overlapping_time so that it includes `ComparingResult` type instead of `Result`.

**Comment by MasahiroLittleforest** [comment]
@RukshanJS Thank you for the suggestion! I updated the documentation for the latest stable version(0.1.0).

**Comment by RukshanJS** [comment]
You are welcome and thanks for this awesome package!
